---
title: "Maps"
date: "01-23-2020"
---

```{r, message = FALSE}
library(tidyverse)
library(leaflet)
```

## Map

While plotly has map plotting feature, we will use a more popular map library `leaflet`.

```{r, eval = FALSE}
leaflet() %>% setView(lng = -121.7405, lat = 38.5449, zoom = 13) %>% 
  addTiles()
```

```{r}
quakes %>% 
  filter(mag > quantile(mag, 0.95)) %>% 
  leaflet() %>%
  addProviderTiles(providers$Wikimedia) %>% 
  addMarkers(~long, ~lat, label = ~mag)
```

### Choropleths

To draw a choropleth, we first need the map data. There is a package `tigris` to download us map data from census.

```{r, message = FALSE, warning = FALSE, results = 'hide'}
library(leaflet)
library(tigris)
states <- states(cb = TRUE)  # lowest resolution us map
class(states)
```

```{r, message = FALSE}
starbucks <- read_csv("starbucks.csv")
(starbucks <- starbucks %>%
  count(Province) %>%
  rename(state = Province, total = n))
```


```{r}
states_starbucks <- states %>% 
  geo_join(starbucks, "STUSPS", "state") %>%
  subset(!is.na(total))
pal <- colorNumeric("Greens", domain=states_starbucks$total)
```

```{r, message = FALSE}
states_starbucks %>%
  leaflet() %>%
  setView(lng = -100, lat = 40, zoom = 4) %>% 
  addProviderTiles(providers$Wikimedia) %>% 
  addPolygons(fillColor = ~pal(total), fillOpacity = 0.7, weight = 1, smoothFactor = 0.2) %>% 
  addLegend(pal = pal, values = states_starbucks$total, position = "bottomright", title = "Starbucks")
```
